name: coverage

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  coveralls:
    timeout-minutes: 30
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2.0.0
    - name: install depends
      run: |
        sudo apt-get update
        sudo apt-get install g++-multilib lcov 
    - name: Cache boost
      id: cache-boost
      uses: actions/cache@v1.1.0
      with:
        path: ~/boost
        key: ${{ runner.os }}-boost-20200130
    - name: Build boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: ./.github/depends/boost.sh -b both -t gcc
    - name: Compile tests
      run: |
        # install gtest to /usr/local
        sudo ./.github/depends/gtest.sh -b 64
        
        mkdir build && cd build
        cmake -DCMAKE_PREFIX_PATH="${HOME}/boost/gcc/lib64/cmake" -DMSGPACK_CXX17=ON -DMSGPACK_32BIT=OFF -DMSGPACK_BOOST=ON -DBUILD_SHARED_LIBS=ON -DMSGPACK_CHAR_SIGN=signed -DMSGPACK_USE_X3_PARSE=ON -DMSGPACK_ENABLE_CXX=ON -DMSGPACK_BUILD_EXAMPLES=ON -DMSGPACK_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DMSGPACK_GEN_COVERAGE=ON ..
        make -j4
        make coverage
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./build/coverage.info.cleaned
